version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    ports:
      - 27017:27017
    command: --smallfiles

  # APP  ***************************************************************************************
  motion-exercise:
    image: motion-exercise-anand:latest
    ports:
      - 8080:8080
    links:
      - mongo
    entrypoint: "mvn spring-boot:run"

